spring:
  security:
    saml2:
      relyingparty:
        registration:
          Saml2spring:
            assertingparty:
              metadata-uri: https://login.microsoftonline.com/70cd6baf-d633-49e5-ab08-2d0d6d4f4ca0/federationmetadata/2007-06/federationmetadata.xml?appid=38347c46-15fd-438b-82fd-26940661bb06
